config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "home#index"
  
  get 'home/index'
  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'
  
  resource :contacts, only: [:new, :create], path_names: {:new => ''}
  resources :articles do
    resources :comments, only: [:create]
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 140}
  validates :text, presence:true,  length: { maximum: 4000}
  has_many :comments

  def subject
  	title
  end

  def last_comment
  	comments.last
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base 
  validates :body, presence:true,  length: { maximum: 4000}
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!, :only => [:new, :create]
 

  def index
    @articles = Article.order 'created_at DESC'
    @comments = Comment.order 'created_at DESC'
  end

  def show
    @article = Article.find(params[:id])
    @comments = Comment.order 'created_at DESC'
  end
  
  def new
      @comments = Comment.order 'created_at DESC'
  end

  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to @article
    else
      @error = @article.errors.full_messages
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @comments = Comment.where "article_id = ?", @article.id
    @comments.each {|c| c.destroy}
    @article.destroy

    redirect_to articles_path
  end

  private 

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
 class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    #@article.comments.create(comment_params)
    @comment = @article.comments.new do |c|
      c.author = current_user.username
      c.body = comment_params[:body]
    end
    @comment.save

    redirect_to article_path(@article)
  end

  def destroy
    @comments.destroy
  end

  private 

  def comment_params
    params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new 
  end

  def create 
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private 

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def terms
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/articles/edit.html.erb
<h1>New article</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-sm-8 col-xs-12">
            
            <!-- heading -->
      <h1>Latest Posts</h1>

        <!-- list of posts -->
        <% @articles.each do |article| %>
        <article>
          <h2><%= link_to "#{article.title}", article_path(article) %> </h2>

          <!-- Иконки над постом -->
          <div class="row">
          <div class="group1 col-sm-6 col-md-6">
            <span class="glyphicon glyphicon-folder-open"></span>  <a href="#">Category</a>
            <span class="glyphicon glyphicon-bookmark"></span> <a href="#">Tag1</a>, 
            <a href="#">Tag2</a>, <a href="#">Tag3</a>
          </div>
          <div class="group2 col-sm-6 col-md-6">
            <span class="glyphicon glyphicon-pencil"></span> <%= link_to "#{article.comments.count} Comments", article_path(article) %>
            <span class="glyphicon glyphicon-time"></span> <%= article.created_at %>
          </div>
          </div>

          <hr />

          <img src="http://vw-reutov.ru/wp-content/uploads/2014/04/1.-audi-a8-900%D1%85300.jpg" class="img-responsive">

          <br />

          <!-- Обрезание постов на главной -->
          <p class="lead">
          <%= 
          truncate(article.text, :length => 200, :separator => ' ') do
            link_to "read more", article_path(article)
          end
        %>
        </p>


        <P>
          <%= link_to 'Edit', edit_article_path(article) %> |
          <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?'} %>
        </P>

        <hr />
      </article>
      <% end %>

        <!-- pager -->
          <ul class="pager"> 
              <li class="previous">
                  <a href="#">← Older</a>
              </li> 
              <li class="next">
                  <a href="#">Newer →</a>
              </li> 
          </ul>
        </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
      <div class="well text-center">
         <p class="lead">
            Don't want to miss updates?  Please click to bellow button!
          </p>
          <button class="btn btn-primary btn-lg">Subscribe to my feed</button>
      </div>

          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>Latest Comments</h4>
            </div>

          <ul class="list-group">
            <% @comments.limit(5).each do |c|%>
                <li class="list-group-item">
               <%= link_to "#{truncate(c.body, :length => 50, :separator => ' ')}", article_path(c.article_id)%>   - <em><%= c.author%></em>

              </li>
              <% end %>
          </ul>     
        </div>
  </div><!—- /.row -—>
</div>

app/views/articles/new.html.erb
<div class="container">
	<div class="row">

      <div class="col-md-6 col-sm-6 col-xs-12">

			<h1>New article</h1>
			<br />
			<% if !@error.nil? %>
				<div class="alert alert-danger" role="alert" id="error">
					
						<p style="color: #A94446">
							<% @error.each do |e|%>
								<%= e %>.
							<% end %>
						</p>
					
				</div>
			<% end %>

			<%= form_for :article, url: articles_path do |f| %>

				<p>
					<label class="sr-only" for="name">Title</label>
					<%= f.text_field :title, class: 'form-control', placeholder: "Title" %>
				</p>

				<p>
					<label class="sr-only" for="name">Post</label>
					<%= f.text_area :text, class: 'form-control', placeholder: "Post", rows: 4 %>
				</p>

				
				 <div class="text-right">
					<%= f.submit 'Submit', class: 'btn btn-primary btn-md'  %>
				 </div>
					
				
			<% end %>
		</div>

		<div class="col-md-2 col-sm-2 col-xs-0">
        </div>
        
		<div class="col-md-4 col-sm-4 col-xs-12">

			<div class="well text-center">
         		<p class="lead">
	            	Don't want to miss updates?  Please click to bellow button!
	          	</p>
	          	<button class="btn btn-primary btn-lg">Subscribe to my feed</button>
	        </div>

	   		 <div class="panel panel-default">
		        	<div class="panel-heading">
		            	<h4>Latest Comments</h4>
		       		 </div>

		        <ul class="list-group">
		        <% if !@comments.nil?%>
		          <% @comments.limit(5).each do |c|%>
	              	<li class="list-group-item">
	            	 <%= link_to "#{truncate(c.body, :length => 50, :separator => ' ')}", article_path(c.article_id)%>   - <em><%= c.author%></em>

	            	</li>
	              <% end %>
	            <% else %>
	            	<li class="list-group-item">Комментариев еще нет</li>
	            <% end %>
		        </ul>     
	        </div>
        </div>
	</div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-sm-8 col-xs-12">
            
            <!-- heading -->
      <h1>Latest Posts</h1>  

          <!-- list of posts -->

        <article>
          <h2><%= @article.title %> </h2>

          <!-- Иконки над постом -->
          <div class="row">
          <div class="group1 col-sm-6 col-md-6">
                        <span class="glyphicon glyphicon-folder-open"></span>  <a href="#">Category</a>
                          <span class="glyphicon glyphicon-bookmark"></span> <a href="#">Tag1</a>, 
                        <a href="#">Tag2</a>, <a href="#">Tag3</a>
                    </div>
                    <div class="group2 col-sm-6 col-md-6">
                        <span class="glyphicon glyphicon-pencil"></span> <%= link_to "#{@article.comments.count} Comments", article_path %>                             
                          <span class="glyphicon glyphicon-time"></span> <%= @article.created_at %>                         
                    </div>
          </div>

          <hr />

        <img src="http://vw-reutov.ru/wp-content/uploads/2014/04/1.-audi-a8-900%D1%85300.jpg" class="img-responsive">

        <br />

        <!-- Обрезание постов на главной -->
        <p >
             <%= @article.text%>
        </p>


        <P>

          <%= link_to 'Edit', edit_article_path(@article) %> |
          <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?'} %>
        </P>
      
        <hr />
      </article>
      <!-- Pager -->
            <ul class="pager"> 
                <li class="previous">
                   <%= link_to "← Back to Posts", articles_path %> 
                </li>  
            </ul>
            <!-- Comments-->
      <ul id="comments" class="comments">
        <% @article.comments.each do |comment|%>
          <li class="comment">
              <div class="clearfix">
                  <h4 class="pull-left"><%= comment.author %></h4>
                  <h5 class="pull-right">Added at: <%= comment.created_at%></h5>
              </div>
              <p>
                  <em><%= comment.body %></em>
              </p>
          </li>
          <hr />
          <% end %>    
      </ul>

      <!-- Add comments -->
        
      <div class="panel panel-default">
        <div class="panel-body">
        <%= form_for([@article, @article.comments.build]) do |f| %>
         
              <div class="col-md-12 form-group clearfix" , style="margin-left: 0">  
              <h4 class="lead">Добавить комментарий:</h4>  
                <label class="sr-only" for="name">Comment</label>  
          <%= f.text_area :body, class: 'form-control', placeholder: 'Comment', style: 'margin-left: 0', rows: 3 %>
          </div>

          <div class="col-md-12 form-group text-right">
          <%= f.submit 'Submit', class: 'btn btn-primary btn-md'  %>
          </div>
        <% end %>
        </div>
      </div>
     </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
          <div class="well text-center">
             <p class="lead">
                Don't want to miss updates?  Please click to bellow button!
              </p>
              <button class="btn btn-primary btn-lg">Subscribe to my feed</button>
          </div>

          <div class="panel panel-default">
            <div class="panel-heading">
                <h4>Latest Comments</h4>

           </div>

          <ul class="list-group">
            <% @comments.limit(5).each do |c|%>
                <li class="list-group-item">
               <%= link_to "#{truncate(c.body, :length => 50, :separator => ' ')}", article_path(c.article_id)%>   - <em><%= c.author%></em>

              </li>
              <% end %>
          </ul>     
        </div>
  </div><!—- /.row -—>
</div>

app/views/contacts/create.html.erb
<p>Thank you!</p>

app/views/contacts/new.html.erb
<div class="container">
	<div class="row">
	<div class="col-md-3 col-sm-3 col-xs-0">
	</div>
      <div class="col-md-6 col-sm-6 col-xs-12">

			<h1><%= t('contacts.contact_us') %></h1>
			<br />

			<%= form_for :contact, url: contacts_path do |f| %>
				
				<% if @contact && @contact.errors.any? %>
				<p>
					<ul>
					<% @contact.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
					</ul>
				</p>
				<% end %>
				<p>
					<label class="sr-only" for="email">Email</label>
					<%= f.text_field :email, autofocus: true, class: 'form-control', placeholder: 'Email' %>
				</p>

				<p>
					<label class="sr-only" for="message">Message</label>
					<%= f.text_area :message, class: 'form-control', placeholder: 'Message', rows: 4  %>
				</p>

				<div class="text-right">
					<%= f.submit 'Send Message', class: 'btn btn-primary btn-md'  %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Congratulation!</p>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>

<script data-require="jquery@*" data-semver="2.1.4" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script data-require="bootstrap@*" data-semver="3.3.5" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link data-require="bootstrap@*" data-semver="3.3.5" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
<link data-require="bootstrap@*" data-semver="3.3.5" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.5/cosmo/bootstrap.min.css" />
<link data-require="bootstrap@*" data-semver="3.3.5" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" /> 



  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>


<nav class="navbar navbar-inverse navbar-fixed-top" >
    <div class="container-fluid" >
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Спрятанная кнопка для отображения на мобильных устройствах -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Supper Blog</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/articles">All Posts <span class="sr-only">(current)</span></a></li>
          <li><a href="/articles/new">New Post</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Others <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <!-- <a href="/terms">Terms</a> -->
                <%=link_to 'Terms', terms_path %>
              </li>
              <li>
                <!-- <a href="/about">About</a> -->
                <%=link_to 'About', about_path %>
              </li>
              <li>
                <!-- <a href="/contacts">Contacts</a> -->
                <%=link_to 'Contact us', new_contacts_path %>
              </li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>

          <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Your account</a></li>
                <li role="separator" class="divider"></li>
                <li><%=link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
              </ul>
          </li>
        
        <% else %>

          <li><%= link_to 'Log In', new_user_session_path %></li>      

        <% end %>
         
        </ul>
      </div>

     </div>
</nav>

  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<%= yield %>

<footer>
  <div class="conteiner">
    <hr />
    <p class="text-center"> Copyrighting © Henry 2015. All rights resive</p> 
  </div>
</footer>

</body>
</html>

app/views/pages/about.html.erb
<h1 style="text-align: center;">About us</h1>

<blockquote style="background-color: ghostwhite; margin-left: 30%; width: 35%;">
<p>We are the champions - my friend</p>
<p>And we'll keep on fighting till the end</p>
<p>We are the champions</p>
<p>We are the champions</p>
<p>No time for losers</p>
<p>Cause we are the champions of the world</p>
</blockquote>

app/views/pages/terms.html.erb
<h2 style="text-align: center;">Terms of Servis!</h2>
  <a class="btn btn-outline btn-block arab" href="https://www.google.ru/search?q=rails+5" style="width: 66%;  margin: 0 auto;">google</a>

app/views/terms/new.html.erb
<h2>Условия использования!</h2>